twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
    filters:
        pdf:
            class: Dompdf\Twig\DompdfFilter
            public: false
